version: '3.3'
services: 
  api:
    container_name: game-center-pwr-server
    restart: always
    build: ./server
    environment: 
      - MONGO_URI=mongodb://mongodb:27017/game-center-pwr
      - NODE_ENV=production
    ports: 
      - "5000:5000"
    depends_on: 
      - mongodb
  client:
    container_name: game-center-pwr-client
    restart: always
    build: ./client
    ports: 
      - "80:80"
    depends_on: 
      - api
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"